{% set name = "loki-logger-handler" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/loki-logger-handler-{{ version }}.tar.gz
  sha256: 26411f141959d843cd833a70ff378eb4fa2e7ab31670815db5ae9f62e57f6140

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  imports:
    - loki_logger_handler
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xente/loki-logger-handler
  summary: Handler designed for transmitting logs to Grafana Loki in JSON format.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
